### PR TITLE
Change json to use virtual modifiers

### PR DESCRIPTION
**Pull request by tomduncalf**
This change allows the script to work alongside Sticky Keys without interfering

### CODE REVIEW

**Comment by tomduncalf** [comment]
Sorry the diff reformatted the JSON, currently only got use of one hand so it was the easiest way to do it. Thanks for the script!

**Comment by tomduncalf** [comment]
(Check the diff with `?w=1` appended to it to see the real changes!)

**Review by qubist — COMMENTED** [review]
Dang, this looks good! Are these variables a feature of Karabiner? I'll test and merge soon, I'm a bit busy with school at the moment.

**Comment by qubist** [comment]
Also glad this is helping you out :)

**Comment by tomduncalf** [comment]
Yeah, they’re in the docs... not sure if they are new or not :)

**Pull request merged**
